logging:
  level:
    web: debug
    io.github.zhengchalei: debug
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:./build/Itachi
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
